oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID}
    admin-key: ${KAKAO_ADMIN_KEY}

jwt:
  header: X-AUTH-TOKEN
  secret: ${JWT_SECRET_KEY}
  refresh: ${JWT_REFRESH_KEY}
  access-token-seconds: 31536000
  refresh-token-seconds: 31536000


cool-sms:
  api-key: ${COOL_SMS_API_KEY}
  api-secret: ${COOL_SMS_API_SECRET}
  from-number: ${COOL_SMS_FROM_NUMBER}
  domain: ${COOL_SMS_DOMAIN}

aws:
  s3:
    bucket: ${AWS_BUCKET}
    base-url: ${AWS_BASE_URL}
    access-key: ${ACCESS_S3_ACCESS_KEY}
    secret-key: ${ACCESS_S3_SECRET_KEY}

