server:
  port: 9000
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  profiles:
    include:
      - infrastructure
      - common
    group:
      dev: dev, domain-dev
      prod: prod, domain-prod
      local: local, domain-local
      localDev: local, domain-local-dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 300MB
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

springdoc:
  packages-to-scan: com.example.wineyapi
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  use-fqn: true

oauth:
  apple:
    iss: ${APPLE_ISS}
    client-id: ${APPLE_CLIENT_ID}

---
spring:
  config:
    activate:
      on-profile: "prod"



---
spring:
  config:
    activate:
      on-profile: "dev"

---
spring:
  config:
    activate:
      on-profile: "local"

---
spring:
  config:
    activate:
      on-profile: "localDev"

